name: Custom Proxy Parser

on:
  workflow_dispatch: # Кнопка для ручного запуска
  schedule:
    - cron: '0 */6 * * *' # Автоматический запуск каждые 6 часов

permissions:
  contents: write

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Scraper and Checker
        run: |
          python tgproto.py
          python testproto.py

      - name: Commit updated proxies
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add proxies-tested.txt proxies.txt

          git diff --cached --quiet && exit 0
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅ Auto-updated proxies: ${timestamp}"
          git push
